# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dda5ba7cde9fa2477d4a5a19bcf4f00e"
name = "lt-cart-product-limit"
handle = "lt-cart-product-limit"
application_url = "https://example.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[pos]
embedded = false
